### ISSUE TITLE
Public Database Sync : not syncing

### ISSUE THREAD

**Issue by ianbradbury-bizzibody** [caiyue1993/IceCream#126]
## Expected behaviour
Use-case 1 : Records created on device(s) are written into the Public database.
Use-case 2 : Records updated on device(s) are updated in the Public database.
Use-case 3 : Records updated in the public database are syncronised to all connected devices.

## Actual behaviour
Use-case 1 : Working
Use-case 2 : failing
Use-case 3 : failing

Records created on device(s) are being written to the public database.
Records updated on any device or directly in the public database do not get synchronised back to connected devices.

## Steps to reproduce the problem
Launch app on multiple devices
Create new record on device 1

**Comment by caiyue1993** [comment]
Hi @ianbradbury-bizzibody ,

Thanks for your quick feedback. However, it works well and passes the 3 user cases that you mentioned above in my side. One kind reminder, user is not allowed to write into public database when their iCloud account is not available. You could check that. Besides, I've updated the readme file and example project in the repository. Please re-check it. 

If you still occur this problem, provide more detailed info to us.

**Comment by ianbradbury-bizzibody** [comment]
Use-cases 2 and 3 still fail.

Currently using versions:
Installing IceCream (1.9.0)
Installing Realm (3.14.2)
Installing RealmSwift (3.14.2)
Installing RxRealm (0.7.6)
Installing RxSwift (4.5.0)

Further detail.

Starting from ZERO records in the database.
If I start the app in 2 simulators - sim A and sim B.
If I create a new record in sim A - the record is mirrored in the CloudKit dashboard.  The new record does not sync to sim B.
If I create a new record in sim B - the record is mirrored in the CloudKit dashboard.  The new record does not sync to sim A.
If I force quit the app on sim A and restart the app - the data is synced.

Only when I force quit the app does a sync occur.

It's as if the silent push notice from the server is not being received or is ignored when received.

**Comment by caiyue1993** [comment]
Try it on the real devices, not on the simulators. @ianbradbury-bizzibody

**Comment by ianbradbury-bizzibody** [comment]
Hot-Damn!

Now I feel like an idiot!

It works like a charm.  Fekking good work people.

**Comment by ianbradbury-bizzibody** [comment]
To add.

Having multiple Sync Engines - public and private - appear to work as expected!
